#!/bin/bash
# A basically sane bash environment.
#
# Mike Hearn, originally copied from Ryan Tomayko
# (https://github.com/rtomayko/dotfiles - original hash: cc190d71)

# Establish dotfile location
dotfiles_location() {
    bash_profile_location=$(readlink ${BASH_SOURCE[0]})
    dotfiles_dir=$(dirname $bash_profile_location)
    git -C $dotfiles_dir rev-parse --show-toplevel
}

for file in $(dotfiles_location)/bash/{initial,path,prompt,exports,aliases,functions,includes,extra}; do
    [ -r "$file"  ] && [ -f "$file"  ] && source "$file";
done;
unset file;

# vim: ts=4 sts=4 shiftwidth=4 expandtab


