#!/usr/bin/env bash

# Add tab completion for many Bash commands
[ -f /usr/local/etc/bash_completion  ] && . /usr/local/etc/bash_completion

# Autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# ~/.shenv is used as a machine specific ~/.bashrc
[ -r ~/.bash_env ] && . ~/.bash_env

# Load those secrets, if they exist
if [ -e $HOME/.secrets ]; then source $HOME/.secrets; fi

# FZF
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_CTRL_R_OPTS='--sort'
export FZF_DEFAULT_COMMAND='ag -g ""'
_fzf_compgen_path() {
    ag -g "" "$1"
}

# vim: syntax=sh ts=4 sts=4 shiftwidth=4 expandtab
