#!/usr/bin/env bash

# We want the various sbins on the path along with /usr/local/bin
[ -d "/usr/local/sbin" ] && PATH="$PATH:/usr/local/sbin"
[ -d "/usr/sbin" ] && PATH="$PATH:/usr/sbin"
[ -d "/sbin" ] && PATH="$PATH:/sbin"

# bin folder in dropbox for synced executables/scripts
[ -d "$HOME/Dropbox/bin" ] && PATH="$HOME/Dropbox/bin:$PATH"

# npm/yarn/node bin directories
[ -d "$NPM_PACKAGES/bin" ] && PATH="$NPM_PACKAGES/bin:$PATH"
[ -d "$HOME/.yarn/bin" ] && PATH="$HOME/.yarn/bin:$PATH"

# macos user python site-packages support
[ -d "$HOME/Library/Python/2.7/bin" ] && PATH="$HOME/Library/Python/2.7/bin:$PATH"
[ -d "$HOME/Library/Python/3.5/bin" ] && PATH="$HOME/Library/Python/3.5/bin:$PATH"
[ -d "$HOME/Library/Python/3.6/bin" ] && PATH="$HOME/Library/Python/3.6/bin:$PATH"

# Rustup support
[ -d "$HOME/.cargo/bin" ] && PATH="$HOME/.cargo/bin:$PATH"

# Go support
[ -d "$HOME/.go/bin" ] && PATH="$HOME/.go/bin:$PATH"

# various local `bin` directories
[ -d "$HOME/bin" ] && PATH="$HOME/bin:$PATH"
[ -d "$HOME/.bin" ] && PATH="$HOME/.bin:$PATH"
[ -d "$HOME/.local/bin" ] && PATH="$HOME/.local/bin"

# Final export
export PATH

# vim: syntax=sh ts=4 sts=4 shiftwidth=4 expandtab
