#!/usr/bin/env bash

# Two-line, full-width prompt based on:
# https://gist.github.com/mkottman/1936195

source $(dotfiles_location)/bash/scripts/git-prompt.sh

# Create horizontal line to fill bash prompt
function parse_git_branch {
    PS_LINE=`printf -- '─%.0s' {1..400}`
    PS_FILL=${PS_LINE:0:$COLUMNS}
}

# Find and print the active virtual environment
function virtualenv_info(){
    if [[ -n "$VIRTUAL_ENV" ]]; then
        # Strip out the path and just leave the env name
        venv="${VIRTUAL_ENV##*/}"
    else
        # In case you don't have one activated
        venv=''
    fi
    [[ -n "$venv" ]] && printf "\n[environment: $venv] "
}

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM='xterm-256color';
fi;

# Color codes
reset="\[\e[0m\]";
black="\[\e[1;30m\]";
red="\[\e[1;31m\]";
green="\[\e[1;32m\]";
yellow="\[\e[1;33m\]";
blue="\[\e[1;34m\]";
purple="\[\e[1;35m\]";
cyan="\[\e[1;36m\]";
white="\[\e[1;37m\]";
darkgray="\[\e[90m\]";

# Highlight the user name when logged in as root.
if [[ "${USER}" == "root" ]]; then
	userStyle="${red}";
else
	userStyle="${yellow}";
fi;

# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
	hostStyle="${red}";
else
	hostStyle="${yellow}";
fi;


PS_TIME="\[\033[\$((COLUMNS-12))G\]   \[\033[0;31m\][\t]"

# Prompt variables
VENV="\$(virtualenv_info)";
PROMPT_BEFORE+="${VENV} ";
PROMPT_BEFORE+="\n"; # newline
PROMPT_BEFORE+="${darkgray}\${PS_FILL}\[\033[0G\]${purple}\u"; # username
PROMPT_BEFORE+="${white}@";
PROMPT_BEFORE+="${hostStyle}\h"; # host
PROMPT_BEFORE+="${white}:";
PROMPT_BEFORE+="${blue}\w"; # working directory full path
PROMPT_AFTER="${PS_TIME}\n${reset}\$ "
PROMPT_FORMAT=" ${white}on %s   "; # working directory full path

# Prompt command
PROMPT_COMMAND='__git_ps1 "$PROMPT_BEFORE" "$PROMPT_AFTER" "$PROMPT_FORMAT"; parse_git_branch'

# Git prompt features (read ~/.git-prompt.sh for reference)
export GIT_PS1_SHOWDIRTYSTATE="true"
export GIT_PS1_SHOWSTASHSTATE="true"
export GIT_PS1_SHOWUNTRACKEDFILES="true"
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_SHOWCOLORHINTS="true"
export VIRTUAL_ENV_DISABLE_PROMPT=1 # disable the default virtualenv prompt

PS2="\[${yellow}\]→ \[${reset}\]";
export PS2;
